package interfaceGraphique;

import javafx.scene.layout.Pane;

public abstract class Fenetre extends Pane {
    public Fenetre fenetre;
    public int pos;
    public abstract void retour();
    public abstract void valider();
    public abstract void touche0();
    public abstract void touche1();
    public abstract void touche2();
    public abstract void touche3();
    public abstract void touche4();
    public abstract void touche5();
    public abstract void touche6();
    public abstract void touche7();
    public abstract void touche8();
    public abstract void touche9();
    public abstract void toucheA();
    public abstract void toucheB();
    public abstract void toucheC();
    public abstract void toucheD();
    public abstract void toucheE();
    public abstract void toucheF();
    public abstract void toucheG();
    public abstract void toucheH();
    public abstract void toucheI();
    public abstract void toucheJ();
    public abstract void toucheK();
    public abstract void toucheL();
    public abstract void toucheM();
    public abstract void toucheN();
    public abstract void toucheO();
    public abstract void toucheP();
    public abstract void toucheQ();
    public abstract void toucheR();
    public abstract void toucheS();
    public abstract void toucheT();
    public abstract void toucheU();
    public abstract void toucheV();
    public abstract void toucheW();
    public abstract void toucheX();
    public abstract void toucheY();
    public abstract void toucheZ();
    public abstract void toucheEff();
    public abstract void toucheEsp();
    public abstract void toucheSuiv();
    public abstract void touche0_1();
    public abstract void touche1_1();
    public abstract void touche2_1();
    public abstract void touche3_1();
    public abstract void touche4_1();
    public abstract void touche5_1();
    public abstract void touche6_1();
    public abstract void touche7_1();
    public abstract void touche8_1();
    public abstract void touche9_1();
    public abstract void toucheInserer();
    public abstract void toucheOk();
    public abstract void toucheEff_1();
    public abstract void touche1ct();
    public abstract void touche2ct();
    public abstract void touche5ct();
    public abstract void touche10ct();
    public abstract void touche20ct();
    public abstract void touche50ct();
    public abstract void touche1e();
    public abstract void touche2e();
    public abstract void touche5e();
    public abstract void touche10e();
    public abstract void touche20e();
    public abstract void touche50e();
}
